name: Node CI

on:
  push:
    branches:
      - master
    paths:
      - 'lib/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        echo $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH
        npm ci
        npm run build --if-present
        npm test
        
      env:
        CI: true
